In [3]:
import numpy as np
import pandas as pd

In [17]:
# 1 .Create a null vector of size 10 but the fifth value which is 1 
null_vector = np.zeros(10)
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [15]:
#2. Create a vector with values ranging from 10 to 49
v = np.arange(10,50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [25]:
v[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [29]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
#5. Find indices of non-zero elements from [1,2,0,0,4,0]
x = [1,2,0,0,4,0]
[i if i>0 i for i in x]

SyntaxError: invalid syntax (<ipython-input-31-86e7e8353d2f>, line 3)

In [7]:
data = {
    'IN': [100, 200, 150, 250, 180, 230, 300, 280, 230, 250],
    'US': [150, 180, 200, 230, 250, 220, 200, 260, 280, 230],
    'IE': [300, 280, 250, 280, 220, 230, 200, 240, 270, 230],  
}
data

{'IN': [100, 200, 150, 250, 180, 230, 300, 280, 230, 250],
 'US': [150, 180, 200, 230, 250, 220, 200, 260, 280, 230],
 'IE': [300, 280, 250, 280, 220, 230, 200, 240, 270, 230]}

In [8]:
md = pd.DataFrame(data, index = [2020, 2023, 2019, 2018, 2010, 1999, 1996,1994,2022,2021])
md

IN   US   IE
2020  100  150  300
2023  200  180  280
2019  150  200  250
2018  250  230  280
2010  180  250  220
1999  230  220  230
1996  300  200  200
1994  280  260  240
2022  230  280  270
2021  250  230  230

In [10]:
avg = md.mean()
avg

IN    217.0
US    220.0
IE    250.0
dtype: float64